
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    web: website
spec:
  replicas: 1
  selector:
    matchLabels:
      web: website
  template:
    metadata:
      labels:
        web: website
    spec:
      containers:
      - name: website
        image: venkatnarayan16/website1
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    web: website
  ports:
    - port: 80
      nodePort: 30010  
